upstream web_backend {
    server repo-ujikombengkel-web-1:9000;
    server repo-ujikombengkel-web-2:9000;
    server repo-ujikombengkel-web-3:9000;
}

server {
    listen 80;
    index index.php index.html;
    server_name _;
    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass web_backend;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
